customhost = "employee.cz8rnuahdnd8.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ngwenjie11-employee"
customregion = "us-east-1a"